(function(){
    var modules={
        "panel-main":    	        {url:"$H/m/panel-main.html",router:1},
        "panel-child":              {url:"$H/m/panel-child.html"},
        
        "participant-data":   		        {url:"$H/m/participant/participant-data.html",Table:"participant-glucosa",form_module:"participant-form",router:1,
                                                child_panel:"panel-child",
                                                questionnaire_setup:"online-questionnaire-setup",
                                                online_questionnaire:"online-questionnaire-app",
                                                participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                                participant_export:"ID,Subject_ID,Screening_Number,Randomisation_Number,Subject_Initials,Gender,DOB"
                                            },
        "participant-form":   		        {url:"$H/m/participant/participant-form.html",Table:"participant-glucosa"},

        "online-questionnaire-setup":       {url:"$H/m/oq-setup.html",Table:"participant-glucosa"},
        "online-questionnaire-app":         {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"notes-glucosa",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"notes-glucosa"},

        "randomisation-table-data-glucosa":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-glucosa",form_module:"randomisation-table-form-glucosa"},
        "randomisation-table-form-glucosa":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-glucosa"},

        "adverse-event-data-glucosa":             {url:"$H/m/library/adverse-event-data.html",Table:"adverse-event-glucosa",form_module:"adverse-event-form-glucosa",task_name:"Adverse Event"},
        "adverse-event-form-glucosa":             {url:"$H/m/library/adverse-event-form.html",Table:"adverse-event-glucosa",task_name:"Adverse Event"},
        "file-notes-data-glucosa":                {url:"$H/m/library/file-notes-data.html",Table:"file-notes-glucosa",form_module:"file-notes-form-glucosa",task_name:"File Notes"},
        "file-notes-form-glucosa":                {url:"$H/m/library/file-notes-form.html",Table:"file-notes-glucosa",task_name:"File Notes"},
        "protocol-amendments-data-glucosa":       {url:"$H/m/library/upload-file-data.html",Table:"protocol-amendments-glucosa",form_module:"protocol-amendments-form-glucosa",task_name:"Protocol Amendments"},
        "protocol-amendments-form-glucosa":       {url:"$H/m/library/upload-file-form.html",Table:"protocol-amendments-glucosa",task_name:"Protocol Amendments"},
        
        "s-visit-date-data-glucosa":              {url:"$H/m/library/date-data.html",Table:"s-visit-date-glucosa",form_module:"s-visit-date-form-glucosa",task_name:"Screening - Visit Date"},
        "s-visit-date-form-glucosa":              {url:"$H/m/library/date-form.html",Table:"s-visit-date-glucosa",task_name:"Screening - Visit Date"},
        "s-anthropometry-data-glucosa":           {url:"$H/m/library/anthropometry-data.html",Table:"s-anthropometry-glucosa",form_module:"s-anthropometry-form-glucosa",task_name:"Screening - Anthropometry"},
        "s-anthropometry-form-glucosa":           {url:"$H/m/library/anthropometry-form.html",Table:"s-anthropometry-glucosa",task_name:"Screening - Anthropometry"},
        "s-ethnicity-data-glucosa":               {url:"$H/m/library/ethnicity-data.html",Table:"s-ethnicity-glucosa",form_module:"s-ethnicity-form-glucosa"},
        "s-ethnicity-form-glucosa":               {url:"$H/m/library/ethnicity-form.html",Table:"s-ethnicity-glucosa",task_name:"Screening - Ethnicity"},
        "s-lifestyle-data-glucosa":               {url:"$H/m/library/lifestyle-data.html",Table:"s-lifestyle-glucosa",form_module:"s-lifestyle-form-glucosa",task_name:"Screening - Lifestyle"},
        "s-lifestyle-form-glucosa":               {url:"$H/m/library/lifestyle-form.html",Table:"s-lifestyle-glucosa",task_name:"Screening - Lifestyle"},
        "s-education-data-glucosa":               {url:"$H/m/library/education-data.html",Table:"s-education-glucosa",form_module:"s-education-form-glucosa",task_name:"Screening - Education"},
        "s-education-form-glucosa":               {url:"$H/m/library/education-form.html",Table:"s-education-glucosa",task_name:"Screening - Education"},
        "s-medications-data-glucosa":              {url:"$H/m/library/medications-data.html",Table:"s-medications-glucosa",form_module:"s-medications-form-glucosa",task_name:"Screening - Concomitant Medication"},
        "s-medications-form-glucosa":              {url:"$H/m/library/medications-form.html",Table:"s-medications-glucosa",task_name:"Screening - Concomitant Medication"},
        "s-concom-file-data-glucosa":		        {url:"$H/m/library/upload-file-data.html",Table:"s-concom-file-glucosa",form_module:"s-concom-file-form-glucosa",task_name:"Screening - Concomitant medication file upload"},
        "s-concom-file-form-glucosa":		        {url:"$H/m/library/upload-file-form.html",Table:"s-concom-file-glucosa",task_name:"Screening - Concomitant medication file upload"},
        "s-medical-history-data-glucosa":         {url:"$H/m/library/medical-history-data.html",Table:"s-medical-history-glucosa",form_module:"s-medical-history-form-glucosa",task_name:"Screening - Medical History"},
        "s-medical-history-form-glucosa":         {url:"$H/m/library/medical-history-form.html",Table:"s-medical-history-glucosa",task_name:"Screening - Medical History"},
        "s-ess-data-glucosa":                     {url:"$H/m/library/ess-data.html",Table:"s-ess-glucosa",form_module:"s-ess-form-glucosa",task_name:"Screening - Epworth Sleepiness Scale"},
        "s-ess-form-glucosa":                     {url:"$H/m/library/ess-form.html",Table:"s-ess-glucosa",task_name:"Screening - Epworth Sleepiness Scale"},
        "s-mmse-data-glucosa":                     {url:"$H/m/library/mmse-data.html",Table:"s-mmse-glucosa",form_module:"s-mmse-form-glucosa",task_name:"Screening - Mini Mental State Examination"},
        "s-mmse-form-glucosa":                     {url:"$H/m/library/mmse-form.html",Table:"s-mmse-glucosa",task_name:"Screening - Mini Mental State Examination"},
        "s-dass-data-glucosa":                    {url:"$H/m/library/dass-data.html",Table:"s-dass-glucosa",form_module:"s-dass-form-glucosa",task_name:"Screening - Depression Anxiety Stress Scale (DASS-21)"},
        "s-dass-form-glucosa":                    {url:"$H/m/library/dass-form.html",Table:"s-dass-glucosa",task_name:"Screening - Depression Anxiety Stress Scale (DASS-21)"},
        "s-psqi-data-glucosa":                    {url:"$H/m/library/psqi-data.html",Table:"s-psqi-glucosa",form_module:"s-psqi-form-glucosa",task_name:"Screening - Pittsburgh Sleep Quality Index (PSQI)"},
        "s-psqi-form-glucosa":                    {url:"$H/m/library/psqi-form.html",Table:"s-psqi-glucosa",task_name:"Screening - Pittsburgh Sleep Quality Index (PSQI)"},
        "s-sleep-diary-data-glucosa":		                {url:"$H/m/library/upload-file-data.html",Table:"s-sleep-diary-glucosa",form_module:"s-sleep-diary-form-glucosa",task_name:"Screeening - Sleep Diary"},
        "s-sleep-diary-form-glucosa":		                {url:"$H/m/library/upload-file-form.html",Table:"s-sleep-diary-glucosa",task_name:"Screeening - Sleep Diary"},
        "s-psggrr-data-glucosa":		                {url:"$H/m/library/psggrr-data.html",Table:"s-psggrr-glucosa",form_module:"s-psggrr-form-glucosa",task_name:"Screeening - Grael Research PSG Report"},
        "s-psggrr-form-glucosa":		                {url:"$H/m/library/psggrr-form.html",Table:"s-psggrr-glucosa",task_name:"Screeening - Grael Research PSG Report"},
        "s-source-doc-data-glucosa":		                {url:"$H/m/library/upload-file-data.html",Table:"s-source-doc-glucosa",form_module:"s-source-doc-form-glucosa",task_name:"Screeening - Source Documents"},
        "s-source-doc-form-glucosa":		                {url:"$H/m/library/upload-file-form.html",Table:"s-source-doc-glucosa",task_name:"Screeening - Source Documents"},

        "v1e-visit-date-data-glucosa":              {url:"$H/m/library/date-data.html",Table:"v1e-visit-date-glucosa",form_module:"v1e-visit-date-form-glucosa",task_name:"Visit 1 Day 1 Evening - Visit Date"},
        "v1e-visit-date-form-glucosa":              {url:"$H/m/library/date-form.html",Table:"v1e-visit-date-glucosa",task_name:"Visit 1 Day 1 Evening - Visit Date"},
        "v1e-anthropometry-data-glucosa":           {url:"$H/m/library/anthropometry-short-data.html",Table:"v1e-anthropometry-glucosa",form_module:"v1e-anthropometry-form-glucosa",task_name:"Visit 1 Day 1 Evening - Anthropometry"},
        "v1e-anthropometry-form-glucosa":           {url:"$H/m/library/anthropometry-short-form.html",Table:"v1e-anthropometry-glucosa",task_name:"Visit 1 Day 1 Evening - Anthropometry"},
        "v1e-ess-data-glucosa":                    {url:"$H/m/library/ess-data.html",Table:"v1e-ess-glucosa",form_module:"v1e-ess-form-glucosa",task_name:"Visit 1 Day 1 Evening - ESS"},
        "v1e-ess-form-glucosa":                    {url:"$H/m/library/ess-form.html",Table:"v1e-ess-glucosa",task_name:"Visit 1 Day 1 Evening - ESS"},
        "v1e-dass-data-glucosa":                    {url:"$H/m/library/dass-data.html",Table:"v1e-dass-glucosa",form_module:"v1e-dass-form-glucosa",task_name:"Visit 1 Day 1 Evening - DASS"},
        "v1e-dass-form-glucosa":                    {url:"$H/m/library/dass-form.html",Table:"v1e-dass-glucosa",task_name:"Visit 1 Day 1 Evening - DASS"},
        "v1e-kss-data-glucosa":                    {url:"$H/m/library/kss-data.html",Table:"v1e-kss-glucosa",form_module:"v1e-kss-form-glucosa",task_name:"Visit 1 Day 1 Evening - KSS"},
        "v1e-kss-form-glucosa":                    {url:"$H/m/library/kss-form.html",Table:"v1e-kss-glucosa",task_name:"Visit 1 Day 1 Evening - KSS"},
        "v1e-psqi-data-glucosa":                    {url:"$H/m/library/psqi-data.html",Table:"v1e-psqi-glucosa",form_module:"v1e-psqi-form-glucosa",task_name:"Visit 1 Day 1 Evening - PSQI"},
        "v1e-psqi-form-glucosa":                    {url:"$H/m/library/psqi-form.html",Table:"v1e-psqi-glucosa",task_name:"Visit 1 Day 1 Evening - PSQI"},
        "v1e-word-pairs-set1-practice":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-practice.html"},
        "v1e-word-pairs-set1-trial1":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial1.html"},
        "v1e-word-pairs-set1-trial2":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial2.html"},
        "v1e-word-pairs-set1-trial3":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial3.html"},
        "v1e-word-pairs-set2-practice":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-practice.html"},
        "v1e-word-pairs-set2-trial1":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial1.html"},
        "v1e-word-pairs-set2-trial2":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial2.html"},
        "v1e-word-pairs-set2-trial3":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial3.html"},
        "v1e-ftt-data-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"v1e-ftt-glucosa",form_module:"v1e-ftt-form-glucosa",task_name:"Visit 1 Day 1 Evening - FTT (12 mins)"},
        "v1e-ftt-form-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"v1e-ftt-glucosa",task_name:"Visit 1 Day 1 Evening FFT (12 mins)"},
        "v1e-ftt-alt-data-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"v1e-ftt-alt-glucosa",form_module:"v1e-ftt-alt-form-glucosa",task_name:"Visit 1 Day 1 Evening - FTT Alt sequence (12 mins)"},
        "v1e-ftt-alt-form-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-alt-form.html",Table:"v1e-ftt-alt-glucosa",task_name:"Visit 1 Day 1 Evening FTT Alt sequence (12 mins)"},

        "v1m-kss-data-glucosa":                    {url:"$H/m/library/kss-data.html",Table:"v1m-kss-glucosa",form_module:"v1m-kss-form-glucosa",task_name:"Visit 1 Day 2 Morning - KSS"},
        "v1m-kss-form-glucosa":                    {url:"$H/m/library/kss-form.html",Table:"v1m-kss-glucosa",task_name:"Visit 1 Day 2 Morning - KSS"},
        "v1m-word-pairs-recall-set1-glucosa":	            {url:"$H/m/word-pairs/morning-wordpairs-set1.html"},
        "v1m-word-pairs-recall-set2-glucosa":	            {url:"$H/m/word-pairs/morning-wordpairs-set2.html"},
        "v1m-word-pairs-set1-data-glucosa":		{url:"$H/m/library/word-pairs-data.html",Table:"v1m-word-pairs-set1-glucosa",form_module:"v1m-word-pairs-set1-form-glucosa",task_name:"Visit 1 Day 2 Morning - Word Pair Set 1"},
        "v1m-word-pairs-set1-form-glucosa":		{url:"$H/m/library/word-pairs-form.html",Table:"v1m-word-pairs-set1-glucosa",task_name:"Visit 1 Day 2 Morning - Word Pair Set 1"},
        "v1m-word-pairs-set2-data-glucosa":		{url:"$H/m/library/word-pairs-data.html",Table:"v1m-word-pairs-set2-glucosa",form_module:"v1m-word-pairs-set2-form-glucosa",task_name:"Visit 1 Day 2 Morning - Word Pair Set 2"},
        "v1m-word-pairs-set2-form-glucosa":		{url:"$H/m/library/word-pairs-form.html",Table:"v1m-word-pairs-set2-glucosa",task_name:"Visit 1 Day 2 Morning - Word Pair Set 2"},
        "v1m-ftt-data-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"v1m-ftt-glucosa",form_module:"v1m-ftt-form-glucosa",task_name:"Visit 1 Day 2 Morning - FTT (6 mins)"},
        "v1m-ftt-form-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"v1m-ftt-glucosa",Table2:"v1e-ftt-glucosa",task_name:"Visit 1 Day 2 - FTT Morning (6 mins"},
        "v1m-ftt-alt-data-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"v1m-ftt-alt-glucosa",form_module:"v1m-ftt-alt-form-glucosa",task_name:"Visit 1 Day 2 Morning - FTT Alt sequence (6 mins)"},
        "v1m-ftt-alt-form-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-alt-form.html",Table:"v1m-ftt-alt-glucosa",Table2:"v1e-ftt-alt-glucosa",task_name:"Visit 1 Day 2 Morning FTT Alt sequence (6 mins"},

        "v2e-visit-date-data-glucosa":              {url:"$H/m/library/date-data.html",Table:"v2e-visit-date-glucosa",form_module:"v2e-visit-date-form-glucosa",task_name:"Visit 2 Day 1 Evening - Visit Date"},
        "v2e-visit-date-form-glucosa":              {url:"$H/m/library/date-form.html",Table:"v2e-visit-date-glucosa",task_name:"Visit 2 Day 1 Evening - Visit Date"},
        "v2e-anthropometry-data-glucosa":           {url:"$H/m/library/anthropometry-short-data.html",Table:"v2e-anthropometry-glucosa",form_module:"v2e-anthropometry-form-glucosa",task_name:"Visit 2 Day 1 Evening - Anthropometry"},
        "v2e-anthropometry-form-glucosa":           {url:"$H/m/library/anthropometry-short-form.html",Table:"v2e-anthropometry-glucosa",task_name:"Visit 2 Day 1 Evening - Anthropometry"},
        "v2e-ess-data-glucosa":                    {url:"$H/m/library/ess-data.html",Table:"v2e-ess-glucosa",form_module:"v2e-ess-form-glucosa",task_name:"Visit 2 Day 1 Evening - ESS"},
        "v2e-ess-form-glucosa":                    {url:"$H/m/library/ess-form.html",Table:"v2e-ess-glucosa",task_name:"Visit 2 Day 1 Evening - ESS"},
        "v2e-dass-data-glucosa":                    {url:"$H/m/library/dass-data.html",Table:"v2e-dass-glucosa",form_module:"v2e-dass-form-glucosa",task_name:"Visit 2 Day 1 Evening - DASS"},
        "v2e-dass-form-glucosa":                    {url:"$H/m/library/dass-form.html",Table:"v2e-dass-glucosa",task_name:"Visit 2 Day 1 Evening - DASS"},
        "v2e-kss-data-glucosa":                    {url:"$H/m/library/kss-data.html",Table:"v2e-kss-glucosa",form_module:"v2e-kss-form-glucosa",task_name:"Visit 2 Day 1 Evening - KSS"},
        "v2e-kss-form-glucosa":                    {url:"$H/m/library/kss-form.html",Table:"v2e-kss-glucosa",task_name:"Visit 2 Day 1 Evening - KSS"},
        "v2e-word-pairs-set1-practice":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-practice.html"},
        "v2e-word-pairs-set1-trial1":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial1.html"},
        "v2e-word-pairs-set1-trial2":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial2.html"},
        "v2e-word-pairs-set1-trial3":	            {url:"$H/m/word-pairs/evening-wordpairs-set1-trial3.html"},
        "v2e-word-pairs-set2-practice":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-practice.html"},
        "v2e-word-pairs-set2-trial1":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial1.html"},
        "v2e-word-pairs-set2-trial2":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial2.html"},
        "v2e-word-pairs-set2-trial3":	            {url:"$H/m/word-pairs/evening-wordpairs-set2-trial3.html"},
        "v2e-ftt-data-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"v2e-ftt-glucosa",form_module:"v2e-ftt-form-glucosa",task_name:"Visit 2 Day 1 Evening - FTT (12 mins)"},
        "v2e-ftt-form-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"v2e-ftt-glucosa",task_name:"Visit 2 Day 1 Evening FFT (12 mins)"},
        "v2e-ftt-alt-data-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"v2e-ftt-alt-glucosa",form_module:"v2e-ftt-alt-form-glucosa",task_name:"Visit 2 Day 1 Evening - FTT Alt sequence (12 mins)"},
        "v2e-ftt-alt-form-glucosa":		                        {url:"$H/m/neurocog/finger-tapping12-alt-form.html",Table:"v2e-ftt-alt-glucosa",task_name:"Visit 2 Day 1 Evening FTT Alt sequence (12 mins)"},

        "v2m-kss-data-glucosa":                    {url:"$H/m/library/kss-data.html",Table:"v2m-kss-glucosa",form_module:"v2m-kss-form-glucosa",task_name:"Visit 2 Day 2 Morning - KSS"},
        "v2m-kss-form-glucosa":                    {url:"$H/m/library/kss-form.html",Table:"v2m-kss-glucosa",task_name:"Visit 2 Day 2 Morning - KSS"},
        "v2m-word-pairs-recall-set1-glucosa":	            {url:"$H/m/word-pairs/morning-wordpairs-set1.html"},
        "v2m-word-pairs-recall-set2-glucosa":	            {url:"$H/m/word-pairs/morning-wordpairs-set2.html"},
        "v2m-word-pairs-set1-data-glucosa":		{url:"$H/m/library/word-pairs-data.html",Table:"v2m-word-pairs-set1-glucosa",form_module:"v2m-word-pairs-set1-form-glucosa",task_name:"Visit 2 Day 2 Morning - Word Pair Set 1"},
        "v2m-word-pairs-set1-form-glucosa":		{url:"$H/m/library/word-pairs-form.html",Table:"v2m-word-pairs-set1-glucosa",task_name:"Visit 2 Day 2 Morning - Word Pair Set 1"},
        "v2m-word-pairs-set2-data-glucosa":		{url:"$H/m/library/word-pairs-data.html",Table:"v2m-word-pairs-set2-glucosa",form_module:"v2m-word-pairs-set2-form-glucosa",task_name:"Visit 2 Day 2 Morning - Word Pair Set 2"},
        "v2m-word-pairs-set2-form-glucosa":		{url:"$H/m/library/word-pairs-form.html",Table:"v2m-word-pairs-set2-glucosa",task_name:"Visit 2 Day 2 Morning - Word Pair Set 2"},
        "v2m-ftt-data-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"v2m-ftt-glucosa",form_module:"v2m-ftt-form",task_name:"Visit 2 Day 2 Morning - FTT (6 mins)"},
        "v2m-ftt-form-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"v2m-ftt-glucosa",Table2:"v2e-ftt-glucosa",task_name:"Visit 2 Day 2 Morning (6 mins"},
        "v2m-ftt-alt-data-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"v2m-ftt-alt-glucosa",form_module:"v2m-ftt-alt-form-glucosa",task_name:"Visit 2 Day 2 Morning - FTT Alt sequence (6 mins)"},
        "v2m-ftt-alt-form-glucosa":		            {url:"$H/m/neurocog/finger-tapping6-alt-form.html",Table:"v2m-ftt-alt-glucosa",Table2:"v2e-ftt-alt-glucosa",task_name:"Visit 2 Day 2 Morning FTT Alt sequence (6 mins"},


    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.hosting_path=$vm.hosting_path.replace('online-questionnaire','')
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    //if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
    //}
})();
